
// This file has been generated by the GUI designer. Do not modify.
namespace ABDM.Ayuda
{
	public partial class DlgAcercaDe
	{
		private global::Gtk.VBox vbox2;

		private global::Gtk.Label lblTitulo1;

		private global::Gtk.Label lblTitulo2;

		private global::Gtk.Button btnAceptar;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget ABDM.Ayuda.DlgAcercaDe
			this.Name = "ABDM.Ayuda.DlgAcercaDe";
			this.Title = global::Mono.Unix.Catalog.GetString ("Acerca de...");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Internal child ABDM.Ayuda.DlgAcercaDe.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.lblTitulo1 = new global::Gtk.Label ();
			this.lblTitulo1.Name = "lblTitulo1";
			this.lblTitulo1.LabelProp = global::Mono.Unix.Catalog.GetString ("ABDM");
			this.vbox2.Add (this.lblTitulo1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.lblTitulo1]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.lblTitulo2 = new global::Gtk.Label ();
			this.lblTitulo2.Name = "lblTitulo2";
			this.lblTitulo2.LabelProp = global::Mono.Unix.Catalog.GetString ("Administrador de Bases de Datos MySQL");
			this.vbox2.Add (this.lblTitulo2);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.lblTitulo2]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			w1.Add (this.vbox2);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(w1[this.vbox2]));
			w4.Position = 0;
			// Internal child ABDM.Ayuda.DlgAcercaDe.ActionArea
			global::Gtk.HButtonBox w5 = this.ActionArea;
			w5.Name = "dialog1_ActionArea";
			w5.Spacing = 10;
			w5.BorderWidth = ((uint)(5));
			w5.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.btnAceptar = new global::Gtk.Button ();
			this.btnAceptar.CanDefault = true;
			this.btnAceptar.CanFocus = true;
			this.btnAceptar.Name = "btnAceptar";
			this.btnAceptar.UseStock = true;
			this.btnAceptar.UseUnderline = true;
			this.btnAceptar.Label = "gtk-ok";
			this.AddActionWidget (this.btnAceptar, -7);
			global::Gtk.ButtonBox.ButtonBoxChild w6 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w5[this.btnAceptar]));
			w6.Expand = false;
			w6.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
			this.FrameEvent += new global::Gtk.FrameEventHandler (this.OnFrameEvent);
			this.btnAceptar.Clicked += new global::System.EventHandler (this.OnBtnAceptarClicked);
		}
	}
}
