
// This file has been generated by the GUI designer. Do not modify.

public partial class VenPrincipal
{
	private global::Gtk.UIManager UIManager;

	private global::Gtk.Action BaseDeDatosAction;

	private global::Gtk.Action RegistrarServidorAction;

	private global::Gtk.Action AyudaAction;

	private global::Gtk.Action AcercaDeAction;

	private global::Gtk.VBox vbox1;

	private global::Gtk.MenuBar menubar2;

	private global::Gtk.HPaned hpaned1;

	private global::Gtk.VBox vbox2;

	private global::Gtk.Label label3;

	private global::Gtk.ScrolledWindow GtkScrolledWindow;

	private global::Gtk.TreeView tvBasesDatos;

	private global::Gtk.Notebook nbVistas;

	private global::Gtk.Label label2;

	private global::Gtk.Statusbar statusbar1;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget VenPrincipal
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.BaseDeDatosAction = new global::Gtk.Action ("BaseDeDatosAction", global::Mono.Unix.Catalog.GetString ("Base de datos"), null, null);
		this.BaseDeDatosAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Base de datos");
		w1.Add (this.BaseDeDatosAction, null);
		this.RegistrarServidorAction = new global::Gtk.Action ("RegistrarServidorAction", global::Mono.Unix.Catalog.GetString ("Registrar servidor"), null, null);
		this.RegistrarServidorAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Registrar servidor");
		w1.Add (this.RegistrarServidorAction, null);
		this.AyudaAction = new global::Gtk.Action ("AyudaAction", global::Mono.Unix.Catalog.GetString ("Ayuda"), null, null);
		this.AyudaAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Ayuda");
		w1.Add (this.AyudaAction, null);
		this.AcercaDeAction = new global::Gtk.Action ("AcercaDeAction", global::Mono.Unix.Catalog.GetString ("_Acerca de..."), null, null);
		this.AcercaDeAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Acerca de...");
		w1.Add (this.AcercaDeAction, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "VenPrincipal";
		this.Title = global::Mono.Unix.Catalog.GetString ("ABDM");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child VenPrincipal.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><menubar name='menubar2'><menu name='BaseDeDatosAction' action='BaseDeDatosAction'><menuitem name='RegistrarServidorAction' action='RegistrarServidorAction'/></menu><menu name='AyudaAction' action='AyudaAction'><menuitem name='AcercaDeAction' action='AcercaDeAction'/></menu></menubar></ui>");
		this.menubar2 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar2")));
		this.menubar2.Name = "menubar2";
		this.vbox1.Add (this.menubar2);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.menubar2]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hpaned1 = new global::Gtk.HPaned ();
		this.hpaned1.CanFocus = true;
		this.hpaned1.Name = "hpaned1";
		this.hpaned1.Position = 213;
		// Container child hpaned1.Gtk.Paned+PanedChild
		this.vbox2 = new global::Gtk.VBox ();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.label3 = new global::Gtk.Label ();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Bases de datos");
		this.vbox2.Add (this.label3);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.label3]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.tvBasesDatos = new global::Gtk.TreeView ();
		this.tvBasesDatos.CanFocus = true;
		this.tvBasesDatos.Name = "tvBasesDatos";
		this.GtkScrolledWindow.Add (this.tvBasesDatos);
		this.vbox2.Add (this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.GtkScrolledWindow]));
		w5.Position = 1;
		this.hpaned1.Add (this.vbox2);
		global::Gtk.Paned.PanedChild w6 = ((global::Gtk.Paned.PanedChild)(this.hpaned1[this.vbox2]));
		w6.Resize = false;
		// Container child hpaned1.Gtk.Paned+PanedChild
		this.nbVistas = new global::Gtk.Notebook ();
		this.nbVistas.CanFocus = true;
		this.nbVistas.Name = "nbVistas";
		this.nbVistas.CurrentPage = 0;
		// Notebook tab
		global::Gtk.Label w7 = new global::Gtk.Label ();
		w7.Visible = true;
		this.nbVistas.Add (w7);
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Inicio");
		this.nbVistas.SetTabLabel (w7, this.label2);
		this.label2.ShowAll ();
		this.hpaned1.Add (this.nbVistas);
		this.vbox1.Add (this.hpaned1);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hpaned1]));
		w9.Position = 1;
		// Container child vbox1.Gtk.Box+BoxChild
		this.statusbar1 = new global::Gtk.Statusbar ();
		this.statusbar1.Name = "statusbar1";
		this.statusbar1.Spacing = 6;
		this.vbox1.Add (this.statusbar1);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.statusbar1]));
		w10.Position = 2;
		w10.Expand = false;
		w10.Fill = false;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 588;
		this.DefaultHeight = 422;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.AcercaDeAction.Activated += new global::System.EventHandler (this.OnAcercaDeActionActivated);
	}
}
